tweet-squared/Tweet-Squared-App

db/migrate/20160616234919_add_real_accounts.rb
db/schema.rb

This migration adds a table `real_accounts` with a string
`twitter_handle` and a foreign key to topics

Create migration for real accounts

---

.gitignore

Reverts tweet-squared/Tweet-Squared-App#1

Revert "Ignore sql lite dbs"

---

db/migrate/20160616234919_add_real_accounts.rb
db/schema.rb

Reverts tweet-squared/Tweet-Squared-App#2

Revert "Create migration for real accounts"

---

.gitignore

Reverts tweet-squared/Tweet-Squared-App#3

Revert "Revert "Ignore sql lite dbs""

---

db/migrate/20160617015753_add_topics.rb
db/migrate/20160617021429_add_tweets.rb
db/migrate/20160617023604_add_twitter_handles.rb
db/schema.rb

Migrations

---

app/models/topic.rb
app/models/tweet.rb
app/models/twitter_handle.rb

Add models

---

db/political_seeds.rb

added political figures
- Donald Trump
- Hillary Clinton
- Bill Clinton
- Bernie Sanders

Populate political seeds file.

---

db/celebs_seeds.rb

- creates one topic object (Celebrities)
- creates twitter_handle objects which includes one real twitter_handle and one plus fake twitter_handle(s)
- this file is required by seeds.rb, which gets run in a rake task to populate our database
this pull requests will add a Topic object for Celebrities and multiple TwitterHandle objects owned by certain celebrities to the seeds.rb file which will be run in a rake task
- added one real account and one parody account for: Ellen, Elon Musk, Queen Elizabeth, David Karp, Taylor Swift, Kanye West
this is an update to PR #15

Create seed data for the Celebrities topic of the topics table

---

db/companies_seeds.rb

- Add one Topic "Companies"
- Add one real listing and one fake listing each for Starbucks, Netflix, Burlington, Pinterest, and BP.
- Each company listing refers to the same topic "Companies"
This is an update to #23

Add real and fake listings for companies.

---

Rakefile

Filler tweet generator

---

.gitignore
Gemfile
Gemfile.lock
Rakefile

Twitter API integration

---

app/actions.rb
app/views/topics/show.html.erb

This is the main feature of our app.
Shows the 2 random tweets.

Topics view path

---

app/actions.rb
app/views/topics/index.html.erb

Topics path

---

app/actions.rb

`verify/<id>` checks if the score is correct, and adds to the `:score`
of session. it also always adds one to the `:times` on session so that
we know how many times the user has played.

Create `verify/<id>` route

---

app/views/topics/show.html.erb

A score board is now visible on the bottom of the screen.
Closes Enhancement #47

Added score keeper for enhancement #47

---

app/actions.rb

Topic bugfix

---

app/actions.rb
app/views/topics/show.html.erb

Fixes PR #53
The symbol used in the erb was previously incorrect.

Fix PR #53

---

Rakefile
db/migrate/20160619204508_add_images_to_tweets.rb
db/schema.rb

Now saves imag URLs in the DB, so that we can show them (in a different PR)

Twitter image

---

app/actions.rb
app/views/game_over.html.erb
app/views/layout.erb
public/javascript/widgets.js

- tell the user the game is over
- print final score
- show a play again button
- add a Twitter share your score button
This addresses Issues #60, #61, #62

Game end screen

---

app/actions.rb
app/views/topics/show.html.erb

Update to PR #65 (now has the `if`-`nil?` syntax instead of `unless`

Json topic

---

Rakefile

Twitter API - new tasks to pull more tweets

---

.gitignore
Gemfile
Gemfile.lock
Rakefile
app/actions.rb
app/models/topic.rb
app/models/tweet.rb
app/models/twitter_handle.rb
app/views/game_over.html.erb
app/views/layout.erb
app/views/topics/index.html.erb
app/views/topics/show.html.erb
db/celebs_seeds.rb
db/companies_seeds.rb
db/migrate/20160617015753_add_topics.rb
db/migrate/20160617021429_add_tweets.rb
db/migrate/20160617023604_add_twitter_handles.rb
db/migrate/20160619204508_add_images_to_tweets.rb
db/news_seeds.rb
db/political_seeds.rb
db/schema.rb
db/seeds.rb
public/javascript/application.js
public/javascript/widgets.js
public/stylesheets/application.css

The first version of our app (0.1) in its most basic form is ready to be pushed to master!!!

Version 0.1 of Tweet^2 - Ready for Public Viewing
